# Generated by Django 4.2.6 on 2023-11-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cart",
            field=models.JSONField(default=list),
        ),
    ]
