# Generated by Django 4.2.6 on 2023-10-19 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('res_owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='categories',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('food', models.ManyToManyField(to='res_owner.food')),
            ],
        ),
    ]
