# Generated by Django 4.2.6 on 2023-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(to='res_owner.food'),
        ),
    ]
