# Generated by Django 4.2.6 on 2023-10-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0002_remove_food_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ManyToManyField(to='res_owner.category'),
        ),
    ]
