# Generated by Django 4.2.6 on 2023-10-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0004_alter_restaurant_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
