# Generated by Django 4.2.6 on 2023-10-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0005_food_image_path_food_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
    ]
