# Generated by Django 4.2.6 on 2023-11-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0006_delete_restaurantowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
