# Generated by Django 4.2.6 on 2023-11-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0009_alter_food_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='res_owner.restaurant'),
        ),
    ]
