# Generated by Django 4.2.6 on 2023-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0012_alter_food_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(null=True, to='res_owner.food'),
        ),
    ]
