# Generated by Django 4.2.6 on 2023-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_owner', '0014_alter_category_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ManyToManyField(to='res_owner.restaurant'),
        ),
    ]
