# Generated by Django 4.2.6 on 2023-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=50000)),
                ("restaurants", models.CharField(max_length=50000)),
                ("quantities", models.CharField(max_length=50000)),
                ("prices", models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
