# Generated by Django 4.2.6 on 2023-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=1024)),
                ("city", models.CharField(max_length=256)),
                ("province_or_state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Not sent"),
                            ("1", "Sent"),
                            ("2", "Accepted"),
                            ("3", "Prepared"),
                            ("4", "Delivered"),
                            ("5", "Rejected"),
                        ],
                        default="1",
                        max_length=9,
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                ("cart", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=4)),
            ],
        ),
    ]
