# Generated by Django 4.2.6 on 2023-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=254)),
                ("city", models.CharField(max_length=254)),
                ("province_or_state", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=128)),
                ("postal_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                ("date_and_time", models.DateTimeField()),
                ("items", models.CharField(max_length=50000)),
                ("restaurants", models.CharField(max_length=50000)),
                ("quantities", models.CharField(max_length=50000)),
                ("prices", models.CharField(max_length=50000)),
            ],
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
