# Generated by Django 4.2.6 on 2023-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Not sent"),
                    ("1", "Sent"),
                    ("2", "Accepted"),
                    ("3", "Prepared"),
                    ("4", "Delivered"),
                    ("5", "Rejected"),
                ],
                default="1",
                max_length=9,
            ),
        ),
    ]
