# Generated by Django 4.2.6 on 2023-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_quantity_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
