# Generated by Django 4.2.6 on 2023-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_location_order_alter_userdata_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.RemoveField(
            model_name="location",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="province_or_state",
        ),
        migrations.RemoveField(
            model_name="location",
            name="street",
        ),
        migrations.AddField(
            model_name="location",
            name="location",
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
