# Generated by Django 4.2.6 on 2023-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_location_city_remove_location_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location",
            new_name="street",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="items",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="restaurants",
            new_name="restaurant",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="prices",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="quantities",
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="postal_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="province_or_state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
