# Generated by Django 4.2.6 on 2023-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_quantity_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
