# Generated by Django 4.2.6 on 2023-10-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_quantity_rename_location_location_street_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Quantity",
        ),
    ]
