# Generated by Django 4.2.6 on 2023-10-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_order_id_order_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="item",
            new_name="items",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="price",
            new_name="prices",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="quantity",
            new_name="quantities",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="restaurant",
            new_name="restaurants",
        ),
    ]
