# Generated by Django 4.2.6 on 2023-10-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_item_shoppingcart_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="prices",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="quantities",
            field=models.CharField(max_length=50000),
        ),
    ]
