# Generated by Django 4.2.6 on 2023-10-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_shoppingcart_prices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="res_ids",
            field=models.CharField(default=0, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdata",
            name="cart",
            field=models.JSONField(default=list),
        ),
    ]
