# Generated by Django 4.2.6 on 2023-10-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_order_res_ids_userdata_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name="ShoppingCart",
        ),
    ]
