# Generated by Django 4.2.6 on 2023-11-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_quantity_delete_shoppingcart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="prices",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantities",
        ),
        migrations.RemoveField(
            model_name="order",
            name="res_ids",
        ),
        migrations.RemoveField(
            model_name="order",
            name="restaurants",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.JSONField(default=list),
        ),
    ]
