# Generated by Django 4.2.6 on 2023-11-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_quantity"),
        ("user", "0011_rename_user_id_order_user_remove_order_items_and_more"),
    ]

    operations = []
